//
// File generated by rootcint at Wed Oct 11 14:39:40 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME mainDic
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "mainDic.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void B_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void B_Dictionary();
   static void *new_B(void *p = 0);
   static void *newArray_B(Long_t size, void *p);
   static void delete_B(void *p);
   static void deleteArray_B(void *p);
   static void destruct_B(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::B*)
   {
      ::B *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::B),0);
      static ::ROOT::TGenericClassInfo 
         instance("B", "./b.h", 7,
                  typeid(::B), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &B_Dictionary, isa_proxy, 0,
                  sizeof(::B) );
      instance.SetNew(&new_B);
      instance.SetNewArray(&newArray_B);
      instance.SetDelete(&delete_B);
      instance.SetDeleteArray(&deleteArray_B);
      instance.SetDestructor(&destruct_B);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::B*)
   {
      return GenerateInitInstanceLocal((::B*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::B*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void B_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::B*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   void A_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void A_Dictionary();
   static void *new_A(void *p = 0);
   static void *newArray_A(Long_t size, void *p);
   static void delete_A(void *p);
   static void deleteArray_A(void *p);
   static void destruct_A(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::A*)
   {
      ::A *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::A),0);
      static ::ROOT::TGenericClassInfo 
         instance("A", "./a.h", 7,
                  typeid(::A), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &A_Dictionary, isa_proxy, 0,
                  sizeof(::A) );
      instance.SetNew(&new_A);
      instance.SetNewArray(&newArray_A);
      instance.SetDelete(&delete_A);
      instance.SetDeleteArray(&deleteArray_A);
      instance.SetDestructor(&destruct_A);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::A*)
   {
      return GenerateInitInstanceLocal((::A*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::A*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void A_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::A*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_A(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::A : new ::A;
   }
   static void *newArray_A(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::A[nElements] : new ::A[nElements];
   }
   // Wrapper around operator delete
   static void delete_A(void *p) {
      delete ((::A*)p);
   }
   static void deleteArray_A(void *p) {
      delete [] ((::A*)p);
   }
   static void destruct_A(void *p) {
      typedef ::A current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::A

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_B(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::B : new ::B;
   }
   static void *newArray_B(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::B[nElements] : new ::B[nElements];
   }
   // Wrapper around operator delete
   static void delete_B(void *p) {
      delete ((::B*)p);
   }
   static void deleteArray_B(void *p) {
      delete [] ((::B*)p);
   }
   static void destruct_B(void *p) {
      typedef ::B current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::B

/********************************************************
* mainDic.cpp
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablemainDic();

extern "C" void G__set_cpp_environmentmainDic() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("a.h");
  G__add_compiledheader("b.h");
  G__cpp_reset_tagtablemainDic();
}
#include <new>
extern "C" int G__cpp_dllrevmainDic() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* B */
static int G__mainDic_168_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   B* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new B[n];
     } else {
       p = new((void*) gvp) B[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new B;
     } else {
       p = new((void*) gvp) B;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__mainDicLN_B));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__mainDic_168_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   B* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new B(*(B*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__mainDicLN_B));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef B G__TB;
static int G__mainDic_168_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (B*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((B*) (soff+(sizeof(B)*i)))->~G__TB();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (B*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((B*) (soff))->~G__TB();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__mainDic_168_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   B* dest = (B*) G__getstructoffset();
   *dest = *(B*) libp->para[0].ref;
   const B& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* A */
static int G__mainDic_169_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   A* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new A[n];
     } else {
       p = new((void*) gvp) A[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new A;
     } else {
       p = new((void*) gvp) A;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__mainDicLN_A));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__mainDic_169_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   A* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new A(*(A*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__mainDicLN_A));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef A G__TA;
static int G__mainDic_169_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (A*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((A*) (soff+(sizeof(A)*i)))->~G__TA();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (A*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((A*) (soff))->~G__TA();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__mainDic_169_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   A* dest = (A*) G__getstructoffset();
   *dest = *(A*) libp->para[0].ref;
   const A& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* B */

/* A */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncmainDic {
 public:
  G__Sizep2memfuncmainDic(): p(&G__Sizep2memfuncmainDic::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncmainDic::*p)();
};

size_t G__get_sizep2memfuncmainDic()
{
  G__Sizep2memfuncmainDic a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancemainDic() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablemainDic() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__mainDicLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__mainDicLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mainDicLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__mainDicLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mainDicLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__mainDicLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__mainDicLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mainDicLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__mainDicLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mainDicLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* B */
static void G__setup_memvarB(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__mainDicLN_B));
   { B *p; p=(B*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->a)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__mainDicLN_A),-1,-1,1,"a=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* A */
static void G__setup_memvarA(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__mainDicLN_A));
   { A *p; p=(A*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->b)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__mainDicLN_B),-1,-1,1,"b=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarmainDic() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncB(void) {
   /* B */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__mainDicLN_B));
   G__memfunc_setup("B",66,G__mainDic_168_0_1, 105, G__get_linked_tagnum(&G__mainDicLN_B), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("B", 66, G__mainDic_168_0_2, (int) ('i'), G__get_linked_tagnum(&G__mainDicLN_B), -1, 0, 1, 1, 1, 0, "u 'B' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~B", 192, G__mainDic_168_0_3, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__mainDic_168_0_4, (int) ('u'), G__get_linked_tagnum(&G__mainDicLN_B), -1, 1, 1, 1, 1, 0, "u 'B' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncA(void) {
   /* A */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__mainDicLN_A));
   G__memfunc_setup("A",65,G__mainDic_169_0_1, 105, G__get_linked_tagnum(&G__mainDicLN_A), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("A", 65, G__mainDic_169_0_2, (int) ('i'), G__get_linked_tagnum(&G__mainDicLN_A), -1, 0, 1, 1, 1, 0, "u 'A' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~A", 191, G__mainDic_169_0_3, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__mainDic_169_0_4, (int) ('u'), G__get_linked_tagnum(&G__mainDicLN_A), -1, 1, 1, 1, 1, 0, "u 'A' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncmainDic() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalmainDic() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcmainDic() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__mainDicLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__mainDicLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__mainDicLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__mainDicLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__mainDicLN_B = { "B" , 99 , -1 };
G__linked_taginfo G__mainDicLN_A = { "A" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablemainDic() {
  G__mainDicLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__mainDicLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__mainDicLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__mainDicLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__mainDicLN_B.tagnum = -1 ;
  G__mainDicLN_A.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablemainDic() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__mainDicLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__mainDicLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__mainDicLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__mainDicLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__mainDicLN_B),sizeof(B),-1,256,(char*)NULL,G__setup_memvarB,G__setup_memfuncB);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__mainDicLN_A),sizeof(A),-1,256,(char*)NULL,G__setup_memvarA,G__setup_memfuncA);
}
extern "C" void G__cpp_setupmainDic(void) {
  G__check_setup_version(30051515,"G__cpp_setupmainDic()");
  G__set_cpp_environmentmainDic();
  G__cpp_setup_tagtablemainDic();

  G__cpp_setup_inheritancemainDic();

  G__cpp_setup_typetablemainDic();

  G__cpp_setup_memvarmainDic();

  G__cpp_setup_memfuncmainDic();
  G__cpp_setup_globalmainDic();
  G__cpp_setup_funcmainDic();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncmainDic();
  return;
}
class G__cpp_setup_initmainDic {
  public:
    G__cpp_setup_initmainDic() { G__add_setup_func("mainDic",(G__incsetup)(&G__cpp_setupmainDic)); G__call_setup_funcs(); }
   ~G__cpp_setup_initmainDic() { G__remove_setup_func("mainDic"); }
};
G__cpp_setup_initmainDic G__cpp_setup_initializermainDic;

