/********************************************************************
* threads_read_data_v2Dic.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error threads_read_data_v2Dic.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablethreads_read_data_v2Dic();
extern void G__cpp_setup_inheritancethreads_read_data_v2Dic();
extern void G__cpp_setup_typetablethreads_read_data_v2Dic();
extern void G__cpp_setup_memvarthreads_read_data_v2Dic();
extern void G__cpp_setup_globalthreads_read_data_v2Dic();
extern void G__cpp_setup_memfuncthreads_read_data_v2Dic();
extern void G__cpp_setup_functhreads_read_data_v2Dic();
extern void G__set_cpp_environmentthreads_read_data_v2Dic();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "threads_read_data_v2.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__threads_read_data_v2DicLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__threads_read_data_v2DicLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__threads_read_data_v2DicLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__threads_read_data_v2DicLN_TList;
extern G__linked_taginfo G__threads_read_data_v2DicLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__threads_read_data_v2DicLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__threads_read_data_v2DicLN_TThread;
extern G__linked_taginfo G__threads_read_data_v2DicLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__threads_read_data_v2DicLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__threads_read_data_v2DicLN_TQObjSender;
extern G__linked_taginfo G__threads_read_data_v2DicLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__threads_read_data_v2DicLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__threads_read_data_v2DicLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__threads_read_data_v2DicLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__threads_read_data_v2DicLN_Worker;
extern G__linked_taginfo G__threads_read_data_v2DicLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__threads_read_data_v2DicLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
