//
// File generated by rootcint at Wed Oct 11 16:35:14 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME mainDic
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "mainDic.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void MyDisplay_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void delete_MyDisplay(void *p);
   static void deleteArray_MyDisplay(void *p);
   static void destruct_MyDisplay(void *p);
   static void streamer_MyDisplay(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::MyDisplay*)
   {
      ::MyDisplay *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::MyDisplay >(0);
      static ::ROOT::TGenericClassInfo 
         instance("MyDisplay", ::MyDisplay::Class_Version(), "./MyDisplay.h", 21,
                  typeid(::MyDisplay), ::ROOT::DefineBehavior(ptr, ptr),
                  &::MyDisplay::Dictionary, isa_proxy, 0,
                  sizeof(::MyDisplay) );
      instance.SetDelete(&delete_MyDisplay);
      instance.SetDeleteArray(&deleteArray_MyDisplay);
      instance.SetDestructor(&destruct_MyDisplay);
      instance.SetStreamerFunc(&streamer_MyDisplay);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::MyDisplay*)
   {
      return GenerateInitInstanceLocal((::MyDisplay*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::MyDisplay*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr MyDisplay::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *MyDisplay::Class_Name()
{
   return "MyDisplay";
}

//______________________________________________________________________________
const char *MyDisplay::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::MyDisplay*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int MyDisplay::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::MyDisplay*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void MyDisplay::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::MyDisplay*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *MyDisplay::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::MyDisplay*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void MyDisplay::Streamer(TBuffer &R__b)
{
   // Stream an object of class MyDisplay.

   TGMainFrame::Streamer(R__b);
}

//______________________________________________________________________________
void MyDisplay::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class MyDisplay.
      TClass *R__cl = ::MyDisplay::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "aNrGraphs", &aNrGraphs);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nPoints", &nPoints);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*mGraphs", &mGraphs);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fEcan", &fEcan);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*mMultiGraph", &mMultiGraph);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*aConsumer", &aConsumer);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "aCond", &aCond);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*update", &update);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*updateStop", &updateStop);
      TGMainFrame::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrapper around operator delete
   static void delete_MyDisplay(void *p) {
      delete ((::MyDisplay*)p);
   }
   static void deleteArray_MyDisplay(void *p) {
      delete [] ((::MyDisplay*)p);
   }
   static void destruct_MyDisplay(void *p) {
      typedef ::MyDisplay current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_MyDisplay(TBuffer &buf, void *obj) {
      ((::MyDisplay*)obj)->::MyDisplay::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::MyDisplay

/********************************************************
* mainDic.cpp
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablemainDic();

extern "C" void G__set_cpp_environmentmainDic() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("MyDisplay.h");
  G__cpp_reset_tagtablemainDic();
}
#include <new>
extern "C" int G__cpp_dllrevmainDic() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* MyDisplay */
static int G__mainDic_374_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   MyDisplay* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 3
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new MyDisplay(
(TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]));
   } else {
     p = new((void*) gvp) MyDisplay(
(TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__mainDicLN_MyDisplay));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mainDic_374_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MyDisplay*) G__getstructoffset())->UpdateGraph();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mainDic_374_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MyDisplay*) G__getstructoffset())->UpdateStop();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mainDic_374_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MyDisplay*) G__getstructoffset())->InitGraph();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mainDic_374_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) MyDisplay::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mainDic_374_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) MyDisplay::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mainDic_374_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) MyDisplay::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mainDic_374_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      MyDisplay::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mainDic_374_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MyDisplay*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mainDic_374_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) MyDisplay::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mainDic_374_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) MyDisplay::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mainDic_374_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) MyDisplay::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mainDic_374_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) MyDisplay::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef MyDisplay G__TMyDisplay;
static int G__mainDic_374_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (MyDisplay*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((MyDisplay*) (soff+(sizeof(MyDisplay)*i)))->~G__TMyDisplay();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (MyDisplay*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((MyDisplay*) (soff))->~G__TMyDisplay();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* MyDisplay */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncmainDic {
 public:
  G__Sizep2memfuncmainDic(): p(&G__Sizep2memfuncmainDic::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncmainDic::*p)();
};

size_t G__get_sizep2memfuncmainDic()
{
  G__Sizep2memfuncmainDic a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancemainDic() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__mainDicLN_MyDisplay))) {
     MyDisplay *G__Lderived;
     G__Lderived=(MyDisplay*)0x1000;
     {
       TGMainFrame *G__Lpbase=(TGMainFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__mainDicLN_MyDisplay),G__get_linked_tagnum(&G__mainDicLN_TGMainFrame),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TGCompositeFrame *G__Lpbase=(TGCompositeFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__mainDicLN_MyDisplay),G__get_linked_tagnum(&G__mainDicLN_TGCompositeFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGFrame *G__Lpbase=(TGFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__mainDicLN_MyDisplay),G__get_linked_tagnum(&G__mainDicLN_TGFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGWindow *G__Lpbase=(TGWindow*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__mainDicLN_MyDisplay),G__get_linked_tagnum(&G__mainDicLN_TGWindow),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGObject *G__Lpbase=(TGObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__mainDicLN_MyDisplay),G__get_linked_tagnum(&G__mainDicLN_TGObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__mainDicLN_MyDisplay),G__get_linked_tagnum(&G__mainDicLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TQObject *G__Lpbase=(TQObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__mainDicLN_MyDisplay),G__get_linked_tagnum(&G__mainDicLN_TQObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablemainDic() {

   /* Setting up typedef entry */
   G__search_typename2("UInt_t",104,-1,0,-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__mainDicLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__mainDicLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mainDicLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__mainDicLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mainDicLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__mainDicLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__mainDicLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mainDicLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__mainDicLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mainDicLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__mainDicLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__mainDicLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__mainDicLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__mainDicLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mainDicLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__mainDicLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mainDicLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__mainDicLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__mainDicLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__mainDicLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__mainDicLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__mainDicLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__mainDicLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__mainDicLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__mainDicLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__mainDicLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mainDicLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__mainDicLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mainDicLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* MyDisplay */
static void G__setup_memvarMyDisplay(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__mainDicLN_MyDisplay));
   { MyDisplay *p; p=(MyDisplay*)0x1000; if (p) { }
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,2,"aNrGraphs=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,2,"nPoints=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,2,0,G__get_linked_tagnum(&G__mainDicLN_TGraph),-1,-1,2,"mGraphs=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mainDicLN_TRootEmbeddedCanvas),-1,-1,2,"fEcan=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mainDicLN_TMultiGraph),-1,-1,2,"mMultiGraph=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mainDicLN_TThread),-1,-1,2,"aConsumer=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,2,"aCond=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mainDicLN_TGTextButton),-1,-1,2,"update=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mainDicLN_TGTextButton),-1,-1,2,"updateStop=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mainDicLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarmainDic() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncMyDisplay(void) {
   /* MyDisplay */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__mainDicLN_MyDisplay));
   G__memfunc_setup("ConsumerFunc",1240,(G__InterfaceMethod) NULL, 89, -1, -1, 0, 1, 3, 2, 0, "Y - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MyDisplay",924,G__mainDic_374_0_2, 105, G__get_linked_tagnum(&G__mainDicLN_MyDisplay), -1, 0, 3, 1, 1, 0, 
"U 'TGWindow' - 10 - - h - 'UInt_t' 0 - - "
"h - 'UInt_t' 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CloseWindow",1134,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("UpdateGraph",1109,G__mainDic_374_0_4, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UpdateStop",1033,G__mainDic_374_0_5, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("InitGraph",902,G__mainDic_374_0_6, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__mainDic_374_0_7, 85, G__get_linked_tagnum(&G__mainDicLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&MyDisplay::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__mainDic_374_0_8, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&MyDisplay::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__mainDic_374_0_9, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&MyDisplay::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__mainDic_374_0_10, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&MyDisplay::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__mainDicLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__mainDic_374_0_14, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__mainDic_374_0_15, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&MyDisplay::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__mainDic_374_0_16, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&MyDisplay::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__mainDic_374_0_17, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&MyDisplay::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__mainDic_374_0_18, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&MyDisplay::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~MyDisplay", 1050, G__mainDic_374_0_19, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncmainDic() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {
}

static void G__cpp_setup_global8() {
}

static void G__cpp_setup_global9() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalmainDic() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
  G__cpp_setup_global8();
  G__cpp_setup_global9();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcmainDic() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__mainDicLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__mainDicLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__mainDicLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__mainDicLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__mainDicLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__mainDicLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__mainDicLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__mainDicLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__mainDicLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__mainDicLN_TGObject = { "TGObject" , 99 , -1 };
G__linked_taginfo G__mainDicLN_TQObject = { "TQObject" , 99 , -1 };
G__linked_taginfo G__mainDicLN_TGWindow = { "TGWindow" , 99 , -1 };
G__linked_taginfo G__mainDicLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__mainDicLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__mainDicLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__mainDicLN_TGFrame = { "TGFrame" , 99 , -1 };
G__linked_taginfo G__mainDicLN_TGCompositeFrame = { "TGCompositeFrame" , 99 , -1 };
G__linked_taginfo G__mainDicLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__mainDicLN_TGTextButton = { "TGTextButton" , 99 , -1 };
G__linked_taginfo G__mainDicLN_TGMainFrame = { "TGMainFrame" , 99 , -1 };
G__linked_taginfo G__mainDicLN_TThread = { "TThread" , 99 , -1 };
G__linked_taginfo G__mainDicLN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__mainDicLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };
G__linked_taginfo G__mainDicLN_TRootEmbeddedCanvas = { "TRootEmbeddedCanvas" , 99 , -1 };
G__linked_taginfo G__mainDicLN_TGraph = { "TGraph" , 99 , -1 };
G__linked_taginfo G__mainDicLN_TMultiGraph = { "TMultiGraph" , 99 , -1 };
G__linked_taginfo G__mainDicLN_MyDisplay = { "MyDisplay" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablemainDic() {
  G__mainDicLN_TClass.tagnum = -1 ;
  G__mainDicLN_TBuffer.tagnum = -1 ;
  G__mainDicLN_TMemberInspector.tagnum = -1 ;
  G__mainDicLN_TObject.tagnum = -1 ;
  G__mainDicLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__mainDicLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__mainDicLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__mainDicLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__mainDicLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__mainDicLN_TGObject.tagnum = -1 ;
  G__mainDicLN_TQObject.tagnum = -1 ;
  G__mainDicLN_TGWindow.tagnum = -1 ;
  G__mainDicLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__mainDicLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__mainDicLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__mainDicLN_TGFrame.tagnum = -1 ;
  G__mainDicLN_TGCompositeFrame.tagnum = -1 ;
  G__mainDicLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__mainDicLN_TGTextButton.tagnum = -1 ;
  G__mainDicLN_TGMainFrame.tagnum = -1 ;
  G__mainDicLN_TThread.tagnum = -1 ;
  G__mainDicLN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__mainDicLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__mainDicLN_TRootEmbeddedCanvas.tagnum = -1 ;
  G__mainDicLN_TGraph.tagnum = -1 ;
  G__mainDicLN_TMultiGraph.tagnum = -1 ;
  G__mainDicLN_MyDisplay.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablemainDic() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__mainDicLN_TClass);
   G__get_linked_tagnum_fwd(&G__mainDicLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__mainDicLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__mainDicLN_TObject);
   G__get_linked_tagnum_fwd(&G__mainDicLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__mainDicLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__mainDicLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__mainDicLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__mainDicLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__mainDicLN_TGObject);
   G__get_linked_tagnum_fwd(&G__mainDicLN_TQObject);
   G__get_linked_tagnum_fwd(&G__mainDicLN_TGWindow);
   G__get_linked_tagnum_fwd(&G__mainDicLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__mainDicLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__mainDicLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__mainDicLN_TGFrame);
   G__get_linked_tagnum_fwd(&G__mainDicLN_TGCompositeFrame);
   G__get_linked_tagnum_fwd(&G__mainDicLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__mainDicLN_TGTextButton);
   G__get_linked_tagnum_fwd(&G__mainDicLN_TGMainFrame);
   G__get_linked_tagnum_fwd(&G__mainDicLN_TThread);
   G__get_linked_tagnum_fwd(&G__mainDicLN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G__mainDicLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__mainDicLN_TRootEmbeddedCanvas);
   G__get_linked_tagnum_fwd(&G__mainDicLN_TGraph);
   G__get_linked_tagnum_fwd(&G__mainDicLN_TMultiGraph);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__mainDicLN_MyDisplay),sizeof(MyDisplay),-1,62464,(char*)NULL,G__setup_memvarMyDisplay,G__setup_memfuncMyDisplay);
}
extern "C" void G__cpp_setupmainDic(void) {
  G__check_setup_version(30051515,"G__cpp_setupmainDic()");
  G__set_cpp_environmentmainDic();
  G__cpp_setup_tagtablemainDic();

  G__cpp_setup_inheritancemainDic();

  G__cpp_setup_typetablemainDic();

  G__cpp_setup_memvarmainDic();

  G__cpp_setup_memfuncmainDic();
  G__cpp_setup_globalmainDic();
  G__cpp_setup_funcmainDic();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncmainDic();
  return;
}
class G__cpp_setup_initmainDic {
  public:
    G__cpp_setup_initmainDic() { G__add_setup_func("mainDic",(G__incsetup)(&G__cpp_setupmainDic)); G__call_setup_funcs(); }
   ~G__cpp_setup_initmainDic() { G__remove_setup_func("mainDic"); }
};
G__cpp_setup_initmainDic G__cpp_setup_initializermainDic;

