/********************************************************************
* main.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error main.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablemain();
extern void G__cpp_setup_inheritancemain();
extern void G__cpp_setup_typetablemain();
extern void G__cpp_setup_memvarmain();
extern void G__cpp_setup_globalmain();
extern void G__cpp_setup_memfuncmain();
extern void G__cpp_setup_funcmain();
extern void G__set_cpp_environmentmain();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "mymainframe.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__mainLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__mainLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__mainLN_TList;
extern G__linked_taginfo G__mainLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__mainLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__mainLN_TQObjSender;
extern G__linked_taginfo G__mainLN_TGWindow;
extern G__linked_taginfo G__mainLN_TGMainFrame;
extern G__linked_taginfo G__mainLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__mainLN_MyMainFrame;

/* STUB derived class for protected member access */
